-- Load Plugins and Configuration
require'plugins.packer'
require'settings.nvim-preferences'
require'settings.colorscheme'
require'settings.keymaps'
require'settings.autocmds'
require'plugins.treesitter'
require'plugins.telescope'
require'plugins.cmp'
require'plugins.lsp'
require'plugins.lsp.signature'
require'plugins.lsp.null-ls'
require'plugins.lightbulb'
require'plugins.lualine'
require'plugins.vimwiki'
require'plugins.bufferline'
require'plugins.nvim-tree'
--require("markdown_preview_config")
