-- Load Plugins and Configuration
require('plugins.packer')
require('settings.nvim-preferences')
require('settings.colorscheme')
require('settings.keymaps')
require('settings.autocmds')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.cmp')
require('plugins.lsp')
require('plugins.lsp.signature')
require('plugins.lightbulb')
require("plugins.lualine")
require("plugins.tabline")
require("plugins.vimwiki")
--require("markdown_preview_config")
